---
Name: regionalfluent
After: '#fluentextensions'
---

LeftAndMain:
  extensions:
    - RegionalLeftAndMain
Fluent:
  extensions:
    - RegionalFluent
FluentRootURLController:
  extensions:
    - FluentRootURLControllerExtension